### ISSUE TITLE
wiring up the TestResult.xml to VS  

### ISSUE THREAD

**Issue by krisri** [CADbloke/CADtest#4]
Dear CADbloke,

I really like the approach of this project. It allows to run tests acad command based. For debugging tests, I do not see a problem attaching with VS, that should work fine. But when we run lots of tests, and one of the tests fails, it would be nice to see the result of the tests either in the Visual Studio TestExplorer, or if not possible in one of the Visual Studio output windows. Do you see possibilities for this?

thx,

Kris

**Comment by CADbloke** [comment]
I haven't investigated running the tests inside a test runner. I imagine it's kinda hard since their host application is AutoCAD. I honestly haven't even looked at this project in a few months, I was waiting for NUnit v3 to settle down and then I got distracted. I like the idea though, let's see what we can come up with,

**Comment by CADbloke** [comment]
Actually, is this what you want? ... https://github.com/reportunit/reportunit

I haven't tried it myself yet but it looks mighty fine
